### ISSUE TITLE
can't tell if dask cluster is working

### ISSUE THREAD

**Issue by timothydmorton** [pangeo-data/astro.pangeo.io-deploy#12]
I can't tell if the cluster or the dashboard is not working as expected for me.

In the notebook, the cluster seems to give me sensible status (10 workers, 20 cores, 70 GB), but it's taking a loooong time to compute the mean of a column of the gaia dr2 dataset, and the dashboard doesn't tell me anything:

![screenshot 2018-10-24 00 36 01](https://user-images.githubusercontent.com/1895387/47406573-fc826a80-d724-11e8-8228-eb8f97376e78.png)

**Comment by mrocklin** [comment]
cc @martindurant

**Comment by martindurant** [comment]
@timothydmorton , did you perhaps not create a Client

**Comment by SimonKrughoff** [comment]
@timothydmorton can you share the notebook you are using?

**Comment by timothydmorton** [comment]
Hey all-- sorry, I forgot to respond here, but @martindurant was right-- I forgot to create a Client.

**Comment by martindurant** [comment]
:)
