### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/astro.pangeo.io-deploy#17]
Hey astro folks (@SimonKrughoff)! How is astro.pangeo.io going? Conversation around the pangeo+astro use case seems to have died down and I want to make sure we aren't missing anything.

A few points that could use a discussion:

- How has this hub worked?
- Are people interested in continuing to use / maintain it?
- Should we redeploy this over to the main Pangeo kubernetes cluster (https://github.com/pangeo-data/pangeo-cloud-federation)?

**Comment by SimonKrughoff** [comment]
@jhamman thanks for checking in!  I have had to move on to other things recently, but I still have a reminder set to add more demo notebooks to the deployment that I keep resetting every week.

One issue I had is that one of the notebooks I was trying to add isn't working as expected and I haven't had time to figure out why.  If I could rubber duck that with someone, it may help me make progress in adding notebooks.

In response to your questions:

> How has this hub worked?
It's been excellent, as far as I can tell.

> Are people interested in continuing to use / maintain it?
I certainly am.  As I said above, I've been distracted with other things, but I'd be interested getting back into it.

> Should we redeploy this over to the main Pangeo kubernetes cluster?
I'm not sure what the pros and cons are.  I am interested in doing the thing that helps you learn as much as I am doing the "easy" thing.

I've not been keeping up with the pangeo gitter, but I can start scanning that again, if you think it would be useful.
