### ISSUE TITLE
Status pages do not render on astro.pangeo.io

### ISSUE THREAD

**Issue by SimonKrughoff** [pangeo-data/astro.pangeo.io-deploy#6]
I can create a cluster and use it to do computations, however, when I point my browser at the status dashboard, I only see the header and not the content of the diagnostic plots:
![image](https://user-images.githubusercontent.com/945715/47188460-fcc9d280-d2ec-11e8-8688-708e3b944450.png)

I can get to the `Info` page, but none of the other render anything visible.  @mrocklin any thoughts?

**Comment by mrocklin** [comment]
I think that this also came up in
https://github.com/pangeo-data/pangeo/issues/432 (thanks @mnlevy1981 for
raising the excellent issue).  I think that that issue has a solution.

**Comment by SimonKrughoff** [comment]
Sounds like this will be fixed with a new release of `nbserverproxy`.

**Comment by mrocklin** [comment]
You can also pin an older version of tornado or add a line git+
https://github.com/jupyterhub/nbserverproxy to the pip section of the
binder/environment.yml file

**Comment by SimonKrughoff** [comment]
OK done on #8

**Comment by SimonKrughoff** [comment]
I'm closing this as I've now seen the pages working.
