### ISSUE TITLE
Packages to add

### ISSUE THREAD

**Issue by SimonKrughoff** [pangeo-data/astro.pangeo.io-deploy#9]
I'm opening this to try to enumerate the packages people want in place for this deployment.
@timothydmorton may weigh in.

Since `cartopy` is the reason this deployment exists, it should be on the list.  Are there others?

**Comment by martindurant** [comment]
intake-astro ?

**Comment by Cadair** [comment]
sunpy and astropy?

**Comment by SimonKrughoff** [comment]
@Cadair [sunpy and astropy](https://github.com/pangeo-data/astro.pangeo.io-deploy/blob/staging/deployments/astro.pangeo.io/image/binder/environment.yml#L9) are already in the environment.  Let me know if they are not working as expected.

**Comment by SimonKrughoff** [comment]
@martindurant I'll certainly add `intake-astro`.

**Comment by Cadair** [comment]
ooops missed that :D

**Comment by timothydmorton** [comment]
Just for the record @SimonKrughoff, I don't have any other suggestions at the moment.

**Comment by timothydmorton** [comment]
let's add `intake-parquet` to the list also.

**Comment by SimonKrughoff** [comment]
OK.  So the list is:
* `cartopy`
* `intake-astro`
* `intake-parquet`

I'll make a PR later today.

**Comment by martindurant** [comment]
Perhaps also intake-xarray? It may come in useful for array-oriented data, especially if stored in zarr format. That's the main workhorse for the earth science/climate stuff on pangeo main.

**Comment by SimonKrughoff** [comment]
PR is #13.

**Comment by SimonKrughoff** [comment]
Merged and deployed.
